### ISSUE TITLE
Error while deserializing header: HeaderTooLarge 

### ISSUE THREAD

**Issue by SanicsP** [TencentQQGYLab/ELLA#33]
i try to run ella in kaggle with these cells 

!git clone https://github.com/TencentQQGYLab/ELLA
!wget --compression=none https://huggingface.co/QQGYLab/ELLA/blob/main/ella-sd1.5-tsc-t5xl.safetensors
!pip install -U gradio fire diffusers
!GRADIO_SERVER_NAME=0.0.0.0 GRADIO_SERVER_PORT=8082 python3 ELLA/inference.py demo /kaggle/working/ella-sd1.5-tsc-t5xl.safetensors

when i run i get this message 

Traceback (most recent call last):
  File "/kaggle/working/ELLA/inference.py", line 419, in <module>
    fire.Fire(dict(test=main, demo=build_demo))
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/kaggle/working/ELLA/inference.py", line 171, in build_demo
    ella = load_ella(ella_path, pipe.device, pipe.dtype)
  File "/kaggle/working/ELLA/inference.py", line 129, in load_ella
    safetensors.torch.load_model(ella, filename, strict=True)
  File "/opt/conda/lib/python3.10/site-packages/safetensors/torch.py", line 197, in load_model
    state_dict = load_file(filename)
  File "/opt/conda/lib/python3.10/site-packages/safetensors/torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

I restarted the notebook but i get the same error

**Comment by budui** [comment]
Please refer to this issue: https://github.com/TencentQQGYLab/ELLA/issues/28
